### ISSUE TITLE
Failed to load the mobile-preview package

### ISSUE THREAD

**Issue by ghost** [kenwheeler/mobile-preview#16]
[Enter steps to reproduce below:]
1. opened Atom
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [mobile-preview](https://github.com/kenwheeler/mobile-preview) package, v0.4.0
### Stack Trace

Failed to load the mobile-preview package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/evebarrett/.atom/packages/mobile-preview/lib/mobile-preview-view.coffee:4:199)
    at /Users/evebarrett/.atom/packages/mobile-preview/lib/mobile-preview-view.coffee:9:5
    at Object.<anonymous> (/Users/evebarrett/.atom/packages/mobile-preview/lib/mobile-preview-view.coffee:92:5)
    at Object.<anonymous> (/Users/evebarrett/.atom/packages/mobile-preview/lib/mobile-preview-view.coffee:94:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-html-preview, v0.1.12
autocomplete-python, v0.9.4
color-picker, v2.0.13
minimap, v4.15.0
mobile-preview, v0.4.0
python-tools, v0.6.5
webbox-color, v0.5.9

# Dev
No dev packages
```

**Comment by jackiect** [comment]
+1

**Comment by dannielhugo** [comment]
+1

Atom Version: 1.1.0
System: ubuntu 14.04 LTS

**Comment by JelaMiraj** [comment]
+1

**Comment by timxor** [comment]
+1

**Comment by lesion** [comment]
+1

**Comment by andela-oakinniranye** [comment]
+1

**Comment by RLNisme** [comment]
+1

**Comment by RLNisme** [comment]
[Enter steps to reproduce below:]
1. mobile-preview
2. install packages

**Atom Version**: 1.3.1
**System**: "Fedora release
**Thrown From**: [mobile-preview](https://github.com/kenwheeler/mobile-preview) package, v0.4.0

### Stack Trace

Failed to load the mobile-preview package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/root/.atom/packages/mobile-preview/lib/mobile-preview-view.coffee:1:1)
    at /root/.atom/packages/mobile-preview/lib/mobile-preview-view.coffee:5:3
    at Object.<anonymous> (/root/.atom/packages/mobile-preview/lib/mobile-preview-view.coffee:5:3)
    at Object.<anonymous> (/root/.atom/packages/mobile-preview/lib/mobile-preview-view.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/root/.atom/packages/mobile-preview/lib/mobile-preview-editor-view.coffee:2:21)
    at Object.<anonymous> (/root/.atom/packages/mobile-preview/lib/mobile-preview-editor-view.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/root/.atom/packages/mobile-preview/lib/mobile-preview.coffee:1:27)
    at Object.<anonymous> (/root/.atom/packages/mobile-preview/lib/mobile-preview.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:663:34)
    at /usr/share/atom/resources/app.asar/src/package.js:115:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:438:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:516:30)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -9:53.9.0 core:select-left (atom-text-editor.editor.mini.is-focused)
     -9:52 core:paste (atom-text-editor.editor.mini.is-focused)
  2x -9:51.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:17.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
```

### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
autoclose-html, v0.19.0
color-picker, v2.0.14
file-icons, v1.6.13
fonts, v1.0.0
mobile-preview, v0.4.0
todo-show, v1.2.0

# Dev
No dev packages
```

**Comment by MtMNC** [comment]
+1

Edit: see https://github.com/kenwheeler/mobile-preview/issues/14, https://github.com/kenwheeler/mobile-preview/issues/15

**Comment by FrankDraws** [comment]
[Enter steps to reproduce below:]
1. Opened Atom
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.10.5
**Thrown From**: [mobile-preview](https://github.com/kenwheeler/mobile-preview) package, v0.4.0

### Stack Trace

Failed to load the mobile-preview package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:5:3
    at Object.<anonymous> (<anonymous>:5:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (<anonymous>:2:21)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (<anonymous>:1:27)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:663:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:115:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "wrap-guide"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
emmet, v2.3.17
mobile-preview, v0.4.0
monokai, v0.18.0

# Dev
No dev packages
```

**Comment by anqilu-xx** [comment]
+1
Atom 1.3.1
Ubuntu 14.04 LTS

**Comment by KevinStirling** [comment]
+1 
Mac OSX 10.10.5
Atom 1.3.3

**Comment by jer1my** [comment]
+1

[Enter steps to reproduce below:]
1. open atom
2. error

**Atom Version**: 1.5.0
**System**: Mac OS X 10.11.2
**Thrown From**: [mobile-preview](https://github.com/kenwheeler/mobile-preview) package, v0.4.0

### Stack Trace

Failed to load the mobile-preview package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/jerimy/.atom/packages/mobile-preview/lib/mobile-preview-view.coffee:1:1)
    at /Users/jerimy/.atom/packages/mobile-preview/lib/mobile-preview-view.coffee:5:3
    at Object.<anonymous> (/Users/jerimy/.atom/packages/mobile-preview/lib/mobile-preview-view.coffee:5:3)
    at Object.<anonymous> (/Users/jerimy/.atom/packages/mobile-preview/lib/mobile-preview-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jerimy/.atom/packages/mobile-preview/lib/mobile-preview-editor-view.coffee:2:21)
    at Object.<anonymous> (/Users/jerimy/.atom/packages/mobile-preview/lib/mobile-preview-editor-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jerimy/.atom/packages/mobile-preview/lib/mobile-preview.coffee:1:27)
    at Object.<anonymous> (/Users/jerimy/.atom/packages/mobile-preview/lib/mobile-preview.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:722:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "themes": [
      "nucleus-dark-ui",
      "atom-dark-fusion-syntax"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "/Users/jerimy/Desktop/_DATA_/_CODE_/"
  }
}
```

### Installed Packages

``` coffee
# User
atom-dark-fusion-syntax, v1.1.0
color-picker, v2.1.1
emmet, v2.4.1
linter, v1.11.3
linter-csslint, v1.2.0
linter-htmlhint, v1.0.2
linter-jshint, v1.2.2
linter-sass-lint, v1.0.3
minimap, v4.19.0
mobile-preview, v0.4.0
nucleus-dark-ui, v0.7.4
webbox-color, v0.5.9

# Dev
No dev packages
```

**Comment by stanleyz510** [comment]
+1

**Comment by kevin-smets** [comment]
+1

**Comment by FredrikFolkeryd** [comment]
+1

**Comment by FrankDraws** [comment]
How do I disable mobile-preview?

**Comment by JelaMiraj** [comment]
+1

**Comment by Iwkke** [comment]
+1

**Comment by vmgamer** [comment]
+1

**Comment by heyVic** [comment]
+1

**Comment by ilovebamboo** [comment]
Failed to load the mobile-preview package
Cannot read property 'prototype' of undefined
Hide Stack Trace
TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/blackrose/.atom/packages/mobile-preview/lib/mobile-preview-view.coffee:1:1)
    at /Users/blackrose/.atom/packages/mobile-preview/lib/mobile-preview-view.coffee:5:3
    at Object.<anonymous> (/Users/blackrose/.atom/packages/mobile-preview/lib/mobile-preview-view.coffee:5:3)
    at Object.<anonymous> (/Users/blackrose/.atom/packages/mobile-preview/lib/mobile-preview-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee](/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/blackrose/.atom/packages/mobile-preview/lib/mobile-preview-editor-view.coffee:2:21)
    at Object.<anonymous> (/Users/blackrose/.atom/packages/mobile-preview/lib/mobile-preview-editor-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee](/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)

**Comment by a-serna** [comment]
+1

**Comment by moriyas1984** [comment]
+1

**Comment by Renjamin** [comment]
+1

**Comment by gilfuser** [comment]
+1

**Comment by rajagopalx** [comment]
+1

**Comment by josivan** [comment]
+1

**Comment by toremielck** [comment]
+1

**Comment by amon-shadow** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.2 x64
**Electron**: 1.6.15
**OS**: Ubuntu 17.10
**Thrown From**: [mobile-preview](https://github.com/kenwheeler/mobile-preview) package 0.4.0


### Stack Trace

Failed to load the mobile-preview package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at extend (/packages/mobile-preview/lib/mobile-preview-view.coffee:1:1)
    at /packages/mobile-preview/lib/mobile-preview-view.coffee:4:7
    at /packages/mobile-preview/lib/mobile-preview-view.coffee:27:11)
    at /packages/mobile-preview/lib/mobile-preview-view.coffee:1:1)
    at /packages/mobile-preview/lib/mobile-preview-view.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/mobile-preview/lib/mobile-preview-editor-view.coffee:2:21)
    at /packages/mobile-preview/lib/mobile-preview-editor-view.coffee:1:1)
    at /packages/mobile-preview/lib/mobile-preview-editor-view.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/mobile-preview/lib/mobile-preview.coffee:1:27)
    at /packages/mobile-preview/lib/mobile-preview.coffee:1:1)
    at /packages/mobile-preview/lib/mobile-preview.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:937:35)
    at /usr/share/atom/resources/app/src/package.js:160:34
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app/src/package.js:145:18)
    at PackageManager.loadAvailablePackage (/usr/share/atom/resources/app/src/package-manager.js:618:16)
    at PackageManager.loadPackage (/usr/share/atom/resources/app/src/package-manager.js:551:25)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:689:23)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:338:17)
    at /usr/share/atom/resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
  2x -8:27.5.0 core:undo (div.tool-panel.tree-view)
     -3:39.6.0 settings-view:open (div.platformio-ide-terminal.status-bar)
     -3:36.2.0 core:paste (input.hidden-input 
```

**Comment by SebinSong** [comment]
+1

**Comment by seansix** [comment]
+1

[Enter steps to reproduce:]

1. open
2. ...

**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: [mobile-preview](https://github.com/kenwheeler/mobile-preview) package 0.4.0


### Stack Trace

Failed to load the mobile-preview package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at extend (/packages/mobile-preview/lib/mobile-preview-view.coffee:1:1)
    at /packages/mobile-preview/lib/mobile-preview-view.coffee:4:7
    at /packages/mobile-preview/lib/mobile-preview-view.coffee:27:11)
    at /packages/mobile-preview/lib/mobile-preview-view.coffee:1:1)
    at /packages/mobile-preview/lib/mobile-preview-view.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/mobile-preview/lib/mobile-preview-editor-view.coffee:2:21)
    at /packages/mobile-preview/lib/mobile-preview-editor-view.coffee:1:1)
    at /packages/mobile-preview/lib/mobile-preview-editor-view.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/mobile-preview/lib/mobile-preview.coffee:1:27)
    at /packages/mobile-preview/lib/mobile-preview.coffee:1:1)
    at /packages/mobile-preview/lib/mobile-preview.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:143:22)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:618:16)
    at PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:551:25)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:689:23)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:351:17
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -1:36.4.0 core:confirm (input.hidden-input)
  2x -1:24.2.0 core:copy (div.panels-item)
     -1:15.5.0 core:confirm (input.hidden-input)
  4x -0:50.9.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-bootstrap3 1.2.12 
atom-clock 0.1.16 
atom-eclipse-syntax 0.0.5 
atom-html-preview 0.2.5 
autumn-highlighter-syntax 1.13.0 
browser-plus 0.0.98 
city-lights-icons 1.1.1 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.3 
file-icons 2.1.17 
git-projects 1.17.0 
hey-pane 1.1.0 
Hydrogen 2.3.0 
jackhammer-syntax 1.1.0 
mobile-preview 0.4.0 
open-in-browser 0.5.2 
project-manager 3.3.5 
project-plus 1.0.0 
scroll-through-time 0.3.0 
styri-syntax 0.2.0 
teletype 0.10.0 
terminal-plus 0.14.5 
tree-view-sort 0.10.0 
zentabs 0.8.9 
```

**Comment by DKMDebugin** [comment]
+1
